"""
Rule Engine for Divination DSL.

Loads compiled rule JSON (per domain), evaluates AND/OR-nested conditions
against input facts, applies conflict resolution by priority/weight, and
returns matched rules + aggregated conclusions.

Operators supported:
  - Comparators: ==, !=, >=, <=, >, <, in, not_in, contains, contains_all,
                 contains_any, starts_with, ends_with
  - Wuxing relational: wuxing_sheng, wuxing_ke, wuxing_bihe, wuxing_tongqi,
                       liuchong, liuhe, yue_mu, ri_mu, yue_jue, ri_jue
  - Logical nesting: {"AND": [...]} / {"OR": [...]}
  - Template placeholders: "${month_zh}" resolved from input data.
"""
from __future__ import annotations

import json
import os
from bisect import bisect_right
from functools import lru_cache
from typing import Any, Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Wuxing / Ganzhi lookup tables
# ---------------------------------------------------------------------------

TIANGAN = ["甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"]
DIZHI = ["子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥"]

# 天干五行
GAN_WX: Dict[str, str] = {
    "甲": "木", "乙": "木",
    "丙": "火", "丁": "火",
    "戊": "土", "己": "土",
    "庚": "金", "辛": "金",
    "壬": "水", "癸": "水",
}

# 地支五行
ZHI_WX: Dict[str, str] = {
    "寅": "木", "卯": "木",
    "巳": "火", "午": "火",
    "申": "金", "酉": "金",
    "亥": "水", "子": "水",
    "辰": "土", "戌": "土", "丑": "土", "未": "土",
}

# 五行相生: 木->火->土->金->水->木
SHENG_ORDER = ["木", "火", "土", "金", "水"]
WUXING_SHENG: Dict[str, str] = {a: b for a, b in
                                zip(SHENG_ORDER, SHENG_ORDER[1:] + SHENG_ORDER[:1])}
# 五行相克: 木->土->水->火->金->木
KE_ORDER = ["木", "土", "水", "火", "金"]
WUXING_KE: Dict[str, str] = {a: b for a, b in
                             zip(KE_ORDER, KE_ORDER[1:] + KE_ORDER[:1])}

# 地支六合
LIUHE: Dict[str, str] = {
    "子": "丑", "丑": "子", "寅": "亥", "亥": "寅",
    "卯": "戌", "戌": "卯", "辰": "酉", "酉": "辰",
    "巳": "申", "申": "巳", "午": "未", "未": "午",
}

# 地支六冲
LIUCHONG: Dict[str, str] = {
    "子": "午", "午": "子", "丑": "未", "未": "丑",
    "寅": "申", "申": "寅", "卯": "酉", "酉": "卯",
    "辰": "戌", "戌": "辰", "巳": "亥", "亥": "巳",
}

# 长生十二宫 (用 生/旺/墓/绝 四节点)
CHANGSHENG: Dict[str, Dict[str, str]] = {
    "金": {"长生": "巳", "帝旺": "酉", "墓": "丑", "绝": "寅"},
    "木": {"长生": "亥", "帝旺": "卯", "墓": "未", "绝": "申"},
    "水": {"长生": "申", "帝旺": "子", "墓": "辰", "绝": "巳"},
    "土": {"长生": "申", "帝旺": "子", "墓": "辰", "绝": "巳"},  # 增删定土寄生于申
    "火": {"长生": "寅", "帝旺": "午", "墓": "戌", "绝": "亥"},
}

# 六甲旬空
XUNKONG: Dict[str, List[str]] = {
    "甲子": ["戌", "亥"],
    "甲戌": ["申", "酉"],
    "甲申": ["午", "未"],
    "甲午": ["辰", "巳"],
    "甲辰": ["寅", "卯"],
    "甲寅": ["子", "丑"],
}


def wuxing_sheng(wx: str) -> Optional[str]:
    """Return the wuxing generated by given wx."""
    return WUXING_SHENG.get(wx)


def wuxing_ke(wx: str) -> Optional[str]:
    """Return the wuxing being overcome by given wx."""
    return WUXING_KE.get(wx)


def zhi_wx(zhi: str) -> Optional[str]:
    return ZHI_WX.get(zhi)


def is_liuhe(a: str, b: str) -> bool:
    return LIUHE.get(a) == b


def is_liuchong(a: str, b: str) -> bool:
    return LIUCHONG.get(a) == b


def is_mu(wx: str, zhi: str) -> bool:
    """Is zhi the tomb (墓) of wx?"""
    return CHANGSHENG.get(wx, {}).get("墓") == zhi


def is_jue(wx: str, zhi: str) -> bool:
    """Is zhi the绝 of wx?"""
    return CHANGSHENG.get(wx, {}).get("绝") == zhi


# ---------------------------------------------------------------------------
# Template resolver
# ---------------------------------------------------------------------------

def _resolve_template(value: Any, facts: Dict[str, Any]) -> Any:
    """Resolve ${path} placeholders against facts (dot-path access)."""
    if isinstance(value, str):
        if value.startswith("${") and value.endswith("}"):
            path = value[2:-1]
            return _get_path(facts, path)
        # mixed string with embedded placeholders
        if "${" in value:
            out = value
            for k in sorted(_extract_paths(value), key=len, reverse=True):
                out = out.replace("${" + k + "}", str(_get_path(facts, k)))
            return out
        return value
    return value


def _extract_paths(s: str) -> List[str]:
    import re
    return re.findall(r"\$\{([^}]+)\}", s)


def _get_path(obj: Any, path: str) -> Any:
    cur = obj
    for part in path.split("."):
        if isinstance(cur, dict):
            cur = cur.get(part)
        else:
            return None
    return cur


# ---------------------------------------------------------------------------
# Condition evaluator
# ---------------------------------------------------------------------------

class ConditionEvaluator:
    """Evaluate a single condition dict against facts."""

    def __init__(self, facts: Dict[str, Any]):
        self.facts = facts

    def eval(self, cond: Any) -> bool:
        if not isinstance(cond, dict):
            return bool(cond)
        # logical wrappers — support both {"AND": [...]} and
        # {"field": "AND", "conditions": [...]} forms
        if "AND" in cond and isinstance(cond["AND"], list):
            return all(self.eval(c) for c in cond["AND"])
        if "OR" in cond and isinstance(cond["OR"], list):
            return any(self.eval(c) for c in cond["OR"])
        if "NOT" in cond:
            return not self.eval(cond["NOT"])
        field_val = cond.get("field")
        if field_val in ("AND", "OR", "NOT") and "conditions" in cond:
            sub = cond["conditions"]
            if field_val == "AND":
                return all(self.eval(c) for c in sub)
            if field_val == "OR":
                return any(self.eval(c) for c in sub)
            if field_val == "NOT":
                return not self.eval(sub)
        # atomic condition
        return self._eval_atom(cond)

    def _eval_atom(self, cond: Dict[str, Any]) -> bool:
        op = cond.get("operator", "==")
        field = cond.get("field")
        actual = _resolve_template(field, self.facts) if isinstance(field, str) and "${" in field \
            else _get_path(self.facts, field or "")
        expected = cond.get("value")
        expected = _resolve_template(expected, self.facts) if isinstance(expected, str) else expected

        # wuxing relational operators: support both
        #   {"operator": "wuxing_ke", "left":..., "right":...}
        #   {"field": "wuxing_ke", "operator": "==", "left":..., "right":...}
        rel_ops = ("wuxing_sheng", "wuxing_ke", "wuxing_bihe", "wuxing_tongqi",
                   "liuchong", "liuhe")
        if op in rel_ops or (op == "==" and field in rel_ops):
            actual_op = op if op in rel_ops else field
            left = _resolve_template(cond.get("left"), self.facts)
            right = _resolve_template(cond.get("right"), self.facts)
            return self._eval_rel(actual_op, left, right)

        # tomb/jue lookup (one-arg with zhi + anchor)
        tomb_ops = ("yue_mu", "ri_mu", "yue_jue", "ri_jue")
        if op in tomb_ops or (op == "==" and field in tomb_ops):
            actual_op = op if op in tomb_ops else field
            zhi = _resolve_template(cond.get("zhi"), self.facts)
            anchor = _resolve_template(cond.get("month") or cond.get("day"), self.facts)
            wx = zhi_wx(zhi or "")
            if not wx or not anchor:
                return False
            anchor_wx = zhi_wx(anchor)
            if actual_op in ("yue_mu", "ri_mu"):
                return is_mu(wx, anchor) or is_mu(anchor_wx or "", zhi or "")
            if actual_op in ("yue_jue", "ri_jue"):
                return is_jue(wx, anchor) or is_jue(anchor_wx or "", zhi or "")
            return False

        # generic comparator
        try:
            if op == "==":
                return actual == expected
            if op == "!=":
                return actual != expected
            if op == ">=":
                return _num(actual) >= _num(expected)
            if op == "<=":
                return _num(actual) <= _num(expected)
            if op == ">":
                return _num(actual) > _num(expected)
            if op == "<":
                return _num(actual) < _num(expected)
            if op == "in":
                return actual in (expected or [])
            if op == "not_in":
                return actual not in (expected or [])
            if op == "contains":
                if isinstance(actual, (list, tuple, set)):
                    return expected in actual
                return expected in (actual or "")
            if op == "contains_all":
                if not isinstance(actual, (list, tuple, set)):
                    return False
                return all(v in actual for v in (expected or []))
            if op == "contains_any":
                if not isinstance(actual, (list, tuple, set)):
                    return False
                return any(v in actual for v in (expected or []))
            if op == "starts_with":
                return str(actual or "").startswith(str(expected))
            if op == "ends_with":
                return str(actual or "").endswith(str(expected))
            if op == "true":
                return bool(actual)
        except Exception:
            return False
        return False

    def _eval_rel(self, op: str, left: Any, right: Any) -> bool:
        if left is None or right is None:
            return False
        # wuxing operators
        if op == "wuxing_sheng":
            # left wx generates right wx? (e.g. 木 -> 火)
            return wuxing_sheng(left) == right
        if op == "wuxing_ke":
            return wuxing_ke(left) == right
        if op == "wuxing_bihe":
            return zhi_wx(left) == zhi_wx(right) and left != right
        if op == "wuxing_tongqi":
            # same qi: 寅 vs 卯 (both wood branch) etc — treat as same wx
            return zhi_wx(left) == zhi_wx(right)
        if op == "liuchong":
            return is_liuchong(left, right)
        if op == "liuhe":
            return is_liuhe(left, right)
        return False


def _num(x: Any) -> float:
    try:
        return float(x)
    except (TypeError, ValueError):
        return 0.0


# ---------------------------------------------------------------------------
# RuleEngine
# ---------------------------------------------------------------------------

class RuleEngine:
    """Loads rules per domain, matches facts, resolves conflicts."""

    DOMAINS = ("liuyao", "ziwei", "bazi")
    RULES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "rules")

    def __init__(self, rules_dir: Optional[str] = None):
        self.rules_dir = rules_dir or self.RULES_DIR
        self._cache: Dict[str, List[Dict[str, Any]]] = {}

    # ---------- loading ----------
    def load_rules(self, domain: str) -> List[Dict[str, Any]]:
        if domain not in self.DOMAINS:
            raise ValueError(f"unknown domain: {domain}; expected one of {self.DOMAINS}")
        if domain in self._cache:
            return self._cache[domain]
        path = os.path.join(self.rules_dir, f"rules_{domain}.json")
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        rules = data.get("rules", [])
        # pre-sort by priority desc for conflict resolution
        rules.sort(key=lambda r: (-r.get("priority", 5), -abs(r.get("weight", 0))))
        self._cache[domain] = rules
        return rules

    # ---------- matching ----------
    def match(self, input_data: Dict[str, Any], domain: str) -> Dict[str, Any]:
        rules = self.load_rules(domain)
        ev = ConditionEvaluator(input_data)

        matched: List[Dict[str, Any]] = []
        for r in rules:
            conds = r.get("conditions", [])
            if self._match_all(conds, ev):
                matched.append(r)

        # conflict resolution: same (domain, category) — highest priority wins,
        # lower priority same-category rules are dropped
        matched = self._resolve_conflicts(matched)

        # aggregate
        conclusions: List[str] = []
        total_weight = 0
        for r in matched:
            total_weight += r.get("weight", 0)
            for act in r.get("actions", []):
                conclusions.append(act.get("conclusion", ""))

        return {
            "matched_rules": [
                {
                    "rule_id": r["rule_id"],
                    "name": r["name"],
                    "category": r.get("category", ""),
                    "weight": r.get("weight", 0),
                    "priority": r.get("priority", 5),
                    "source": r.get("source", ""),
                    "detail": r.get("actions", [{}])[0].get("detail", ""),
                }
                for r in matched
            ],
            "conclusions": conclusions,
            "total_weight": total_weight,
            "matched_count": len(matched),
        }

    # ---------- internals ----------
    @staticmethod
    def _match_all(conds: List[Any], ev: ConditionEvaluator) -> bool:
        if not conds:
            return False
        for c in conds:
            if not ev.eval(c):
                return False
        return True

    @staticmethod
    def _resolve_conflicts(rules: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Within the same (category), keep only the highest-priority rule when
        rules are mutually exclusive (negative weights with same conclusion
        sign conflict). Simplification: for each category, keep the highest
        priority rule only if its weight sign opposes others; otherwise keep all.
        """
        by_cat: Dict[str, List[Dict[str, Any]]] = {}
        for r in rules:
            cat = r.get("category", "")
            by_cat.setdefault(cat, []).append(r)

        out: List[Dict[str, Any]] = []
        for cat, rs in by_cat.items():
            rs.sort(key=lambda r: -r.get("priority", 5))
            top = rs[0]
            # always keep top; keep lower-priority only if they are not
            # explicitly opposed (i.e. same sign as top or zero weight)
            out.append(top)
            top_sign = (top.get("weight", 0) > 0) - (top.get("weight", 0) < 0)
            for r in rs[1:]:
                w = r.get("weight", 0)
                sign = (w > 0) - (w < 0)
                if sign == top_sign or w == 0:
                    out.append(r)
                # else: opposed sign with lower priority -> dropped
        # restore priority ordering
        out.sort(key=lambda r: (-r.get("priority", 5), r["rule_id"]))
        return out

    # ---------- listing ----------
    def list_rules(self, domain: str) -> Dict[str, Any]:
        rules = self.load_rules(domain)
        return {
            "domain": domain,
            "count": len(rules),
            "rules": [
                {
                    "rule_id": r["rule_id"],
                    "name": r["name"],
                    "category": r.get("category", ""),
                    "weight": r.get("weight", 0),
                    "priority": r.get("priority", 5),
                    "source": r.get("source", ""),
                }
                for r in rules
            ],
        }


# ---------------------------------------------------------------------------
# Convenience singleton
# ---------------------------------------------------------------------------

_engine_singleton: Optional[RuleEngine] = None


def get_engine() -> RuleEngine:
    global _engine_singleton
    if _engine_singleton is None:
        _engine_singleton = RuleEngine()
    return _engine_singleton


if __name__ == "__main__":
    # quick smoke test
    eng = RuleEngine()
    print("liuyao:", len(eng.load_rules("liuyao")))
    print("ziwei:", len(eng.load_rules("ziwei")))
    print("bazi:", len(eng.load_rules("bazi")))

    # sample liuyao input
    sample = {
        "month_zh": "申", "day_zh": "子",
        "month_wx": "金", "day_wx": "水",
        "yong_shen": {"zhi": "申", "wx": "金", "dong": True, "xun_kong": False,
                      "yue_po": True, "wangshuai": "旺"},
        "yuan_shen": {"wx": "土", "dong": False},
        "ji_shen": {"wx": "火", "dong": False},
        "chou_shen": {"dong": False},
        "has_ri_dong_sheng": False,
        "ke_yong_dong_count": 0,
        "yong_two_xian": False, "yong_bu_xian": False,
        "du_fa_or_du_jing": False,
        "daxiang": "平", "net_score": 2,
        "ru_mu": False, "feng_he": False, "hua_jin_shen": False,
        "hua_tui_shen": False, "shi_kong": False,
        "wuxing_zhonghe": True, "sizhu_liutong": True,
        "shun_ni": "顺", "guoji_buji": False,
    }
    res = eng.match(sample, "liuyao")
    print("matched:", res["matched_count"], "total_weight:", res["total_weight"])
