#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build numbered legal_open base files for astro_composite (P2-1), sentence-level lines."""
import os
BASE = os.path.dirname(os.path.abspath(__file__))

def write_numbered(fname, title_lines, body_lines):
    lines = []
    lines.append("# Source: openly-accessible educational web text (non-paywalled), fetched text. Symbolic-layer only, Western tropical zodiac.")
    lines.append("# License note: publicly published on author site; reading corpus for a private concept draft only. Do not republish.")
    lines.extend(title_lines)
    lines.append("")
    lines.extend(body_lines)
    out = os.path.join(BASE, fname)
    with open(out, "w", encoding="utf-8") as f:
        for i, ln in enumerate(lines, start=1):
            f.write(f"{i:05d}\t{ln}\n")
    print(f"{fname}: {len(lines)} lines")
    return len(lines)

nuastro_title = [
 "03 Are They The One? Your Composite Chart in Astrology",
 "Source: Nuastro (nuastro.com), by Elene Beridze",
 "URL: https://nuastro.com/composite-chart-in-astrology-are-they-the-one/",
]
nuastro = [
 "A composite chart is a single chart for the relationship itself, built from the midpoints of two people's planets, not how either person feels about the other.",
 "It answers a different question than synastry: synastry asks how do we affect each other, the composite asks what is this relationship, and where is it going.",
 "It is read like a natal chart, with one rule: every placement describes the couple as a unit.",
 "The composite Sun (purpose), Moon (emotional safety), Venus/Mars (affection and drive), and Saturn (durability) carry the most weight.",
 "It can be transited, because the composite functions as its own chart, outer-planet transits to it mark real turning points in the relationship's life.",
 "It is a mathematical construct, not a real-sky snapshot, so retrogrades do not appear, and it needs accurate birth times for the Ascendant and houses to be reliable.",
 "Most people know their birth chart. Some have looked at synastry, the side-by-side comparison of two charts.",
 "There is a third layer many overlook: the composite chart, a single chart that belongs not to either person alone but to the relationship itself.",
 "If you have ever felt that a relationship has its own personality, its own rhythm, its own recurring tensions and joys, the composite chart is the astrological explanation for it.",
 "At Nuastro the composite is one of the more honest tools in relationship analysis, precisely because it takes the individual ego out of the picture.",
 "What Is a Composite Chart? (Short Answer)",
 "A composite chart is a single chart representing a relationship as its own entity, calculated by taking the mathematical midpoint between each pair of planets and points in two birth charts.",
 "If your Sun is at 10 Aries and your partner's at 20 Leo, the composite Sun sits at the midpoint between them.",
 "The result describes the relationship itself, its purpose, emotional tone, strengths, and challenges, rather than how either person feels.",
 "It is read like a natal chart, can be tracked through transits over time, and pairs with synastry for a complete picture.",
 "What Is a Composite Chart in Astrology?",
 "A composite chart is built by finding the mathematical midpoint between each planet and point in two individual birth charts.",
 "The midpoint of Person A's Sun and Person B's Sun becomes the composite Sun; the same calculation repeats for the Moon, Mercury, Venus, Mars, the outer planets, the Ascendant, Midheaven, and nodal axis.",
 "The result is a single new chart that does not describe how you feel about the other person or how they feel about you; it describes the relationship as a third entity.",
 "The technique was formally introduced to modern Western astrology in 1973 by John Townley in The Composite Chart.",
 "It was expanded and popularised by Robert Hand in his 1975 Planets in Composite, which remains the reference text for working astrologers and gave the composite its interpretive framework.",
 "Before the composite existed, relationship astrology was largely limited to synastry, checking how one chart's planets interact with another's.",
 "The composite changed the question entirely: instead of how do we affect each other, it asks what is this relationship.",
 "Composite Chart vs. Synastry: What is the Difference?",
 "Synastry shows what happens between two people as individuals.",
 "If your Venus lands on someone's Mars, synastry tells you there is an activated attraction: your Venus wakes up their Mars, their Mars activates your Venus.",
 "The chemistry is real, but it lives in the interaction between two separate charts.",
 "The composite shows the nature of the relationship itself, independent of either person's chemistry.",
 "A couple with difficult synastry can have a surprisingly stable, supportive composite.",
 "A couple with gorgeous synastry can have a composite that is volatile or fundamentally ungrounded.",
 "The two are complementary, not interchangeable.",
 "One practical distinction: synastry uses two charts simultaneously, while the composite uses one chart derived mathematically from both.",
 "Because it is a single chart, the composite can receive transits and progressions, letting you time events within the relationship's own life.",
 "Because the composite is constructed from midpoints rather than actual positions, retrogrades do not appear in it.",
 "A planet retrograde in one or both natal charts will not be marked retrograde in the composite, because the composite is a mathematical construction, not a real-sky snapshot.",
 "How to Calculate a Composite Chart",
 "Calculating a composite manually is straightforward, though most astrologers use software.",
 "The midpoint method: take the zodiac longitude (0 to 360) of each planet in both charts; add the two longitudes and divide by two to find the midpoint.",
 "If the midpoint falls more than 180 from either planet, add 180, this gives the near midpoint rather than the far one; repeat for every planet, angle, and point.",
 "For house cusps, astrologers use either the midpoint method (the midpoint between the two natal Ascendants sets the composite Ascendant) or the reference-place method.",
 "A technical quirk: because Mercury and Venus never stray far from the Sun, it is mathematically possible for a composite to place Mercury or Venus in opposition to the composite Sun, impossible in any real chart.",
 "Reading the Composite Chart: Key Placements",
 "The composite is read like a natal chart with one critical adjustment: every placement describes the relationship, not the individuals.",
 "Sun: the life force, purpose, and identity of the bond; its house shows where the relationship most wants to express itself (7th means formal commitment; 5th means romance and play).",
 "Moon: the emotional underpinning, how safe the two feel together and what the bond needs for security (Moon trine Venus means ease and affection; Moon square Saturn means guardedness).",
 "Ascendant: the face the relationship shows the world, and often the circumstances of the first meeting, how others see you as a pair.",
 "Venus and Mars: how affection (Venus) and shared drive or conflict style (Mars) move as a unit; Venus-Mars harmony is a strong romantic signature.",
 "Saturn: where the relationship is tested and what gives it structural durability; well-placed, it is one of the strongest longevity signals.",
 "Nodal axis: the relationship's direction, what it is moving toward and what patterns it may need to release.",
 "The composite Sun's house is the single most telling placement: a 7th-house composite Sun leans toward formal partnership and deep mutual commitment, a 5th-house one toward pleasure, creativity, and romance.",
 "Composite Saturn carries real weight: difficult contacts show where the relationship must do its hardest work, but a well-placed Saturn is one of the most stabilising signatures there is, strongly associated with long-term commitment.",
 "Composite Houses: Where the Relationship Lives",
 "Houses in the composite work as they do in a natal chart: they show the arenas of life where the relationship's energy concentrates.",
 "When multiple composite planets cluster in one house (a stellium), that area becomes a defining feature of the bond.",
 "The 7th house is often the most significant in a romantic composite, showing the nature of formal commitment.",
 "The 8th speaks to shared resources, transformation, and depth of bonding; the 5th governs pleasure, romance, playfulness, and creativity together.",
 "Heavy activity in the mutable houses (3rd, 6th, 9th, 12th) can indicate instability; the 6th and 12th in particular, when strongly occupied, can bring tension, hidden dynamics, or a relationship requiring significant sacrifice or adjustment.",
 "That does not make such a chart unworkable; it raises the stakes of conscious effort.",
 "Composite Chart Aspects: What to Prioritize",
 "Aspects in the composite are interpreted as in a natal chart: conjunctions merge, oppositions create polarity, squares produce friction, trines flow, though the orbs are usually tighter (no more than 5 to 8 degrees for major aspects).",
 "Sun conjunct Moon: a New Moon composite, one of the strongest signatures for unified direction and strong union.",
 "Sun trine or sextile Moon: one of the most supportive general signs of a relationship that functions with ease.",
 "Venus trine or sextile Mars: affection and desire moving in the same direction, a prime romantic-longevity signature.",
 "Sun square Mars: persistent friction and power struggles in the dynamic.",
 "Sun-Saturn (hard): weight and testing; well-handled, also durability, but demands maturity.",
 "Uranus on the Asc-Desc axis: instability or unconventionality; resists formal structure, can be short-lived.",
 "Neptune hard to the Sun: blurred purpose or idealisation that can lead to disillusionment.",
 "The guiding principle: any aspect to the composite Sun is primary, because it colours the entire chart.",
 "Transits to the Composite Chart",
 "One of the most useful features of composite work is that the chart can be tracked over time through transits, just as outer planets move through your natal chart.",
 "Saturn transiting the composite Sun often marks a reckoning, pressure, restructuring.",
 "It is a reality check that can end a foundationless relationship or deepen and formalise a real one.",
 "Jupiter transiting composite Venus or the 5th house tends to coincide with expansive, joyful periods.",
 "Pluto transiting the composite 7th or 8th can bring profound transformation, sometimes a deepening, sometimes a breakdown that leads to complete restructuring.",
 "Uranus transiting the composite Sun is often associated with sudden disruptions to the relationship's identity or direction.",
 "The composite captures not just what the relationship is, but when its chapters turn.",
 "Composite Chart Strengths and Limitations",
 "No single astrological tool tells the whole story, and the composite is no exception.",
 "Its strength is that it treats the relationship itself as the subject of analysis rather than using the individuals as proxies.",
 "That makes it uniquely suited to understanding the recurring patterns neither person fully controls, the things that just keep happening in a given relationship.",
 "Its limitation is that it does not tell you how either person experiences the bond internally (that is synastry's domain), nor what each individual brings from their own natal chart.",
 "A complete relationship analysis uses all three: natal charts, synastry, and composite.",
 "The composite requires accurate birth times for a reliable Ascendant and houses.",
 "If one person's birth time is unknown, the composite Ascendant cannot be trusted, though the planetary picture remains useful.",
 "Can a composite chart predict the future of a relationship?",
 "It can show the relationship's structure and, through transits to the composite, time its turning points.",
 "Saturn crossing the composite Sun often brings a make-or-break reckoning, for example.",
 "It maps tendencies and timing, not a fixed fate; the people involved still choose.",
 "The Composite Chart as a Relationship Mirror",
 "The composite does something rare: it removes the ego from the equation.",
 "You are not looking at what you want from the other person, or what they want from you; you are looking at what the relationship wants.",
 "Relationships have their own momentum and their own timing, and the composite makes both visible.",
 "It is a tool for understanding rather than a verdict.",
 "Pair it with both natal charts and the synastry between them, and you have the full interpretive picture of any significant connection.",
]

thalira_title = [
 "04 Composite Chart Astrology: How to Read Your Relationship's Birth Chart",
 "Source: Thalira (thalira.com) Quantum Codex, by Thalira Research Team",
 "URL: https://thalira.com/blogs/quantum-codex/composite-chart-astrology",
]
thalira = [
 "A composite chart is calculated by finding the midpoint between each pair of corresponding planets in two birth charts and then drawing a new chart using those midpoints.",
 "The result is the birth chart of the relationship itself, not of either individual, but of the partnership as its own entity with its own Sun, Moon, Ascendant, and planetary placements.",
 "What Is a Composite Chart?",
 "A composite chart treats a relationship as a living entity.",
 "Just as a person has a birth chart describing their nature and trajectory, a relationship has a composite chart that reveals the character of the bond itself, its purpose, its challenges, its strengths, and the themes it is here to explore.",
 "The underlying principle of planetary midpoints had been used in European astrology for centuries.",
 "Unlike synastry (which overlays two charts to see how two individuals' energies interact), the composite chart dissolves the two people temporarily into a single chart that speaks about the connection itself.",
 "The Core Premise",
 "When two people enter a relationship, something new comes into existence between them, a third entity that is neither person alone but the living dynamic they create together.",
 "Some relationships bring out creativity, others bring out conflict, others bring profound stability; the composite chart describes that third entity: what it is made of, what it is here for, and how it moves through the world.",
 "Composite vs. Synastry",
 "Synastry and composite charts answer fundamentally different questions and are both valuable.",
 "Synastry asks: How do these two individuals affect each other? It shows attraction, friction, wounding, and healing between specific chart points.",
 "Composite asks: What is this relationship as a thing in itself? It describes the quality of the bond, its purpose, and its destiny.",
 "Think of synastry as the chemistry between two musicians, and the composite chart as the music they make when they play together.",
 "The chemistry produces the music, but the music has its own distinct character beyond either individual musician's style.",
 "Experienced relationship astrologers use both.",
 "Synastry reveals the interpersonal dynamics and how each person activates the other; the composite reveals what the relationship itself is for and where it tends to go.",
 "A synastry with challenging aspects can produce a composite chart of great beauty and purpose, and vice versa.",
 "How the Composite Chart Is Calculated",
 "The most commonly used method is the Midpoint Composite.",
 "For each planetary position, find the midpoint between Person A and Person B's position in the zodiac circle.",
 "The midpoint between two planets is the exact degree equidistant from both, the meeting point of their energies.",
 "Example: Person A has Sun at 10 Aries, Person B has Sun at 20 Gemini; the arc between them is 70 degrees, half is 35, so the composite Sun is at 15 Taurus.",
 "This calculation is performed for Sun, Moon, Mercury, Venus, Mars, Jupiter, Saturn, Uranus, Neptune, Pluto, North Node, Ascendant, and Midheaven.",
 "The resulting midpoint positions are then plotted as a new chart.",
 "The Davison Chart (alternative method) calculates the midpoint between the two birth dates and times in calendar terms, creating an actual birth moment that the relationship could theoretically be born at.",
 "Many astrologers use the midpoint composite for depth interpretation and the Davison chart for timing.",
 "The Composite Sun",
 "The composite Sun represents the central purpose and identity of the relationship, what the connection is fundamentally about and what it is here to express and achieve together.",
 "Aries is a pioneering, energetic relationship; Taurus is built for stability and material security; Gemini is an intellectually alive connection; Cancer is a deeply nurturing, protective bond.",
 "Leo is a radiant, creative connection; Virgo is a practical, service-oriented bond; Libra is built around partnership ideals and harmony; Scorpio is an intensely meaningful bond that confronts shadows.",
 "Sagittarius is an expansive, philosophical connection; Capricorn is a serious, achievement-oriented relationship; Aquarius is a friendship-first, unconventional bond; Pisces is a spiritually sensitive, idealistic connection.",
 "The Composite Moon",
 "The composite Moon describes the emotional life of the relationship, how the partnership feels on a daily basis, what emotional needs it tends to, and where it seeks comfort and security.",
 "The house of the composite Moon is often considered even more important than its sign; it shows the arena where the relationship's emotional core expresses.",
 "Composite Moon in the 4th house suggests a relationship deeply rooted in domestic life and shared private world.",
 "A composite Moon in challenging aspect to Saturn often indicates emotional restraint within the relationship; partners may struggle to express vulnerability to each other even when feelings are deep.",
 "Moon trine Jupiter in the composite chart often creates an emotionally generous, optimistic feeling tone; the relationship tends to be emotionally expansive and mutually uplifting.",
 "The Composite Ascendant",
 "The composite Ascendant describes how the relationship presents itself to the world, its outer face, how others perceive the couple together, and the style of engagement the bond tends to adopt.",
 "A relationship with Scorpio rising in the composite is perceived by others as intense, private, and magnetic.",
 "The Ascendant's ruling planet and its condition in the composite chart describes how well the relationship expresses its face to the world.",
 "Venus in the Composite Chart",
 "Venus describes the aesthetic values, love language, and pleasure-seeking quality of the relationship.",
 "A well-placed composite Venus (especially in Taurus, Libra, or Pisces) suggests the relationship brings genuine beauty, harmony, and affection.",
 "Venus in the composite 5th house puts joy, romance, and creative pleasure at the heart of the bond.",
 "A challenged composite Venus (square Saturn, for example) may indicate the partners have difficulty expressing affection openly, or that they experience love primarily through shared duty rather than delight.",
 "Mars in the Composite Chart",
 "Mars reveals the drive, ambition, and sexual energy of the relationship, how the bond moves into action, what motivates shared effort, and where friction tends to emerge.",
 "Composite Mars in the 10th house often produces a career-driving couple; their shared ambitions are the primary forward momentum.",
 "Mars conjunct the composite Moon can indicate emotional volatility, the relationship's feelings and its drive conflict directly.",
 "Saturn in the Composite Chart",
 "Perhaps the most significant planet to locate in a composite chart.",
 "A prominent composite Saturn (conjunct the Sun, in the 1st house, or ruling the Ascendant) indicates a relationship with serious karmic weight, a bond that feels destined, tends toward commitment, and carries significant lessons.",
 "These relationships often do not begin easily but, once established, endure.",
 "Saturn in the composite 7th house can feel restrictive in the partnership dynamic but is associated with long-term committed relationships.",
 "Saturn-Venus challenges in the composite sometimes describe duty relationships, bonds where love and obligation become indistinguishable.",
 "Pluto in the Composite Chart",
 "Composite Pluto, especially when conjunct personal planets (Sun, Moon, Venus), signals a meaningful relationship, one that fundamentally alters both people.",
 "These bonds can be intensely bonding and may also carry power dynamics, possessiveness, or the experience of being completely undone by the connection.",
 "Composite Pluto conjunct the Sun: the relationship carries enormous meaningful power, possibly disrupting both people's sense of self.",
 "Composite Houses and Their Meaning",
 "The house emphasis in a composite chart shows where the relationship's main energy is concentrated in lived experience.",
 "1st House emphasis: the relationship is very present in the world; the couple's identity is strongly felt as a unit.",
 "2nd House emphasis: shared resources, values, and financial life are central to the relationship's experience.",
 "4th House emphasis: home, family, roots, and private life are the heart of the connection.",
 "5th House emphasis: romance, creativity, children, and play define the bond; the relationship feels youthful and expressive.",
 "7th House emphasis: the relationship is highly conscious of partnership itself as a primary theme; can be intensely egalitarian or intensely conflicted.",
 "8th House emphasis: deep transformation, shared financial dealings, sexuality, and the facing of death or endings define this bond.",
 "10th House emphasis: the relationship has a public, career, or legacy dimension; the couple is known as a unit in the world.",
 "12th House emphasis: a private, spiritual, or hidden relationship; either deeply transcendent or marked by secrets, sacrifice, and difficulty in public expression.",
 "Important Composite Aspects",
 "Aspects between composite planets describe the internal dynamics of the relationship, how different areas of the bond relate to and affect each other.",
 "Composite Sun trine Moon: natural emotional and purposeful harmony; the relationship flows easily between initiative and response.",
 "Composite Sun square Saturn: the relationship's purpose (Sun) encounters restriction and lesson (Saturn), a serious bond that requires sustained effort and carries weight.",
 "Composite Venus trine Jupiter: great warmth, generosity, and shared joy; this relationship tends to feel lucky and expansive.",
 "Composite Moon conjunct Pluto: emotional intensity at the root of the bond; the feelings in this relationship are deep, potentially obsessive, and meaningful.",
 "Composite Mercury-Saturn: communication in this relationship is measured, serious, or restrained; excellent for practical collaboration, potentially stifling for playful exchange.",
 "Transits to the Composite Chart",
 "Outer planet transits to the composite chart mark significant periods in a relationship's life, times of expansion, contraction, transformation, or restructuring.",
 "Saturn transiting the composite Sun is often felt as a period of serious reckoning; the relationship faces its commitments and either deepens or ends.",
 "Pluto conjunct the composite Moon: a period of deep emotional transformation in the relationship, often involving a dismantling of old emotional patterns between the partners.",
 "Reading a Difficult Composite",
 "A composite chart full of squares, oppositions, and prominent Saturn or Pluto placements does not mean the relationship is doomed.",
 "It means the relationship carries significant intensity and challenge as part of its nature; many of the world's most profound and lasting bonds have difficult composite charts.",
 "The challenge is the point: these relationships are about growth through friction, transformation through depth, or commitment through difficulty.",
 "The question to ask of any composite chart, easy or difficult, is: What is this relationship here to do?",
 "Difficulty in a composite describes the nature of the work, not the worthiness of the bond.",
 "Composite Charts for Different Relationships",
 "Composite charts can be constructed for any significant ongoing relationship, not only romantic partnerships.",
 "Business partnerships: the composite chart describes the enterprise's nature and trajectory as well as the working dynamic between partners.",
 "Parent-child relationships: the composite between a parent and child often reflects the specific developmental themes the relationship carries.",
 "Long-term friendships: composite charts between close friends reveal the friendship's character, what makes it sustaining, and what purpose it serves for both people.",
 "The Wisdom of the Composite Chart",
 "The composite chart offers something neither individual chart can: a view of what two people create together beyond themselves.",
 "Every lasting relationship develops its own culture, its own language, its own recurring themes.",
 "The composite chart maps that culture astrologically, naming its qualities, its purpose, and its challenges before they have fully unfolded in time.",
 "Used thoughtfully, it helps partners understand that some of what is hard in their connection is not personal failure but the nature of what they have created together.",
 "Is a composite chart with lots of 12th house planets bad?",
 "Not bad, but distinctive; a 12th house composite emphasis suggests a relationship with a hidden, spiritual, or sacrificial dimension.",
 "These bonds often feel fated and may not be fully visible to the outside world.",
 "The Composite Sun and Moon in Practice",
 "Among all composite chart placements, the Composite Sun and Composite Moon are the most important for understanding the fundamental nature and emotional life of the relationship as an entity.",
 "The Composite Sun by house shows where the relationship expresses its core vitality and purpose most naturally.",
 "A Composite Sun in the 5th house indicates a relationship that comes alive through play, creativity, and self-expression.",
 "A Composite Sun in the 10th house indicates a relationship with a strong public dimension, one that gains much of its vitality from shared professional or social ambitions.",
 "A Composite Sun in the 12th house indicates a relationship with a private, hidden, or spiritual character; the partners may prefer the relationship to remain largely private.",
 "The Composite Moon by house and sign shows the emotional needs of the relationship and how comfort and nurturing are exchanged.",
 "A Composite Moon in Cancer indicates that the relationship needs home, privacy, and a strong sense of us against the world to feel emotionally safe.",
 "A Composite Moon in Aquarius indicates that the relationship needs intellectual freedom, unconventional arrangements, and space for both partners to maintain their individual identities.",
 "A Composite Moon in difficult aspect to Saturn suggests that emotional attunement requires sustained conscious effort.",
 "Composite Venus and Mars in the Relationship",
 "Composite Venus well placed indicates a relationship where affection flows naturally, where both partners feel genuinely valued, and where shared pleasures are sources of nourishment.",
 "Composite Venus in difficult aspect to Saturn suggests that expressing affection may feel blocked or require deliberate effort that does not come naturally.",
 "Composite Venus opposite or square Pluto indicates a relationship where love and intensity are deeply intertwined, and where power dynamics around desire and worth may be ongoing themes.",
 "Composite Mars describes how the relationship handles initiative, conflict, and shared physical energy.",
 "A strong Composite Mars in the 1st house gives the relationship a dynamic, decisive quality; the partners together act more readily than either might alone.",
 "Composite Mars square or opposite Saturn describes a relationship where initiative feels blocked or where one partner's drive consistently meets the other's resistance, requiring patient negotiation.",
]

syn_title = [
 "05 Composite Chart vs Synastry Chart: Which Reveals More About Your Relationship?",
 "Source: SynastryChart (synastrychart.org) guide",
 "URL: https://synastrychart.org/blog/composite-chart-vs-synastry-chart",
]
syn = [
 "Two people sit across from an astrologer and ask: What do our charts say about us? The astrologer pulls up two different charts, and the couple is confused.",
 "One chart overlays two wheels on top of each other; the other blends them into a single wheel. They look nothing alike. They seem to tell different stories.",
 "That is because they do.",
 "A synastry chart takes two natal charts on top of each other without merging them and shows how two individuals interact.",
 "A composite chart shows what the relationship itself looks like as its own entity.",
 "Both are valuable. Neither is complete on its own.",
 "Choosing the wrong one for the wrong question leads to readings that feel off.",
 "What Is a Synastry Chart?",
 "A synastry chart places two natal charts on top of each other without merging them.",
 "You see Person A's planets in one color and Person B's planets in another, and you look at the aspects (angles) between them.",
 "It is a dialogue chart.",
 "It shows how your Mars talks to their Venus, how your Moon sits relative to their Saturn, where the friction is, where the flow is.",
 "The two individuals stay separate; you are reading the conversation between them.",
 "What Synastry Is Best For: understanding how two people experience each other, and identifying areas of attraction, tension, and growth.",
 "It is also useful for seeing which parts of your chart get activated by a specific person, especially in early-stage relationships.",
 "Synastry answers the question: What happens when we are in the same room?",
 "What Is a Composite Chart?",
 "A composite chart takes the mathematical midpoint between every pair of corresponding planets, the midpoint of both Suns, both Moons, both Mercurys, and so on, and plots them as a single chart.",
 "The result is one wheel that represents the relationship as its own entity.",
 "The idea, first popularized by John Townley in the 1970s and refined by Robert Hand in Planets in Composite, is that a relationship is more than just two people reacting to each other.",
 "It has its own personality, its own needs, its own trajectory; the composite chart maps that.",
 "What the Composite Is Best For: understanding the nature of the relationship itself; seeing the relationship's strengths, challenges, and purpose.",
 "It is especially useful for long-term relationships where the we has become its own thing.",
 "The composite answers: What does this relationship want to become?",
 "The Core Difference, Side by Side",
 "Synastry maps two individuals interacting; the composite maps the relationship as one entity.",
 "Synastry uses two overlaid wheels with direct aspect comparison; the composite uses one merged wheel with the midpoint of each planet pair.",
 "The best metaphor for synastry is a conversation between two people; for the composite it is a portrait of the couple.",
 "The short version: synastry shows how you relate; the composite shows what you are together.",
 "They are not competing tools; they are complementary lenses.",
 "How Each Chart Is Calculated",
 "Synastry: Direct Overlay. No calculation happens between the two charts; you place Chart A and Chart B on the same wheel and measure the angles.",
 "If your Sun is at 15 Aries and their Moon is at 17 Leo, that is a trine (120 degrees apart, within 2 degree orb). The skill is in reading aspect patterns, not in computing anything.",
 "Composite: Midpoint Blending. Every planet pair gets averaged.",
 "If your Sun is at 10 Aries and your partner's Sun is at 20 Gemini, the composite Sun sits at 15 Taurus, the zodiacal midpoint.",
 "The same calculation runs for every planet, the Ascendant, and the Midheaven.",
 "This creates a chart that neither person owns. It belongs to the relationship.",
 "What Each Chart Is Best For, By Situation",
 "Dating or Early Relationship (0 to 6 months): Use synastry; the composite will feel abstract because the we has not fully formed yet.",
 "Committed Relationship (6 months to 3 years): Use both; read the composite for the big-picture direction and the synastry for the day-to-day texture.",
 "Long-Term or Marriage (3+ years): Lead with the composite; the relationship genuinely is its own entity, and synastry is used to troubleshoot specific friction points.",
 "Non-Romantic Relationships: Both work; synastry is excellent for business partnerships, friendships, and parent-child dynamics.",
 "John Townley originally intended the composite for all relationship types, not just romantic ones.",
 "A Rule of Thumb",
 "If you are asking why does this person affect me this way, read the synastry.",
 "If you are asking what is this relationship becoming, read the composite.",
 "Reading a Synastry Chart, 5 Focus Areas",
 "Sun-Moon Cross-Aspects: the backbone of emotional compatibility; one person's Sun conjunct or trine the other's Moon is one of the strongest indicators of mutual understanding and long-term warmth.",
 "Venus-Mars Aspects: the chemistry axis; conjunctions and trines flow easily, squares create intense, sometimes volatile passion.",
 "Saturn Aspects: the glue, or the weight; they bring stability and commitment but also restriction and pressure, and are common in long-term relationships.",
 "House Overlays: where one person's planets fall in the other's chart colors which life domains the relationship activates.",
 "Planets in your 7th house directly impact the partnership; planets in your 12th stir unconscious material.",
 "Outer Planet Contacts: Uranus, Neptune, and Pluto aspects to personal planets create generational or transformative dynamics.",
 "These are slow-burn deep structural themes rather than daily interaction.",
 "Reading a Composite Chart, 5 Focus Areas",
 "The composite is read like a natal chart, but for the relationship.",
 "Composite Sun: The Relationship's Identity. The sign and house of the composite Sun describe what the relationship is about; composite Sun in the 10th means a public, achievement-oriented identity, in the 4th means anchored in home and family.",
 "Composite Moon: The Emotional Baseline. It describes how the relationship feels on a daily basis, warm and nurturing, independent and cerebral, or intense and transformative.",
 "Composite Venus: How Love Is Expressed. It shows the relationship's love language, what the couple enjoys together, how they express affection, and what they value as a unit.",
 "Composite Saturn: The Relationship's Challenges. It points to the area where the relationship faces its most persistent difficulties, and where the most growth happens if both people are willing.",
 "Composite Saturn in the 7th house, ironically, is common in marriages that last.",
 "Composite Angles (ASC and MC). The composite Ascendant is how the relationship presents itself to the outside world; the composite Midheaven is the relationship's public direction or shared ambition.",
 "The Composite Planet table: Sun is identity and purpose; Moon is emotional baseline; Mercury is communication style; Venus is love expression and shared values; Mars is shared drive and conflict style; Jupiter is growth areas; Saturn is challenges, commitment, structure; Ascendant is how others see the relationship.",
 "Real Example, Beyonce and Jay-Z",
 "Their synastry shows a strong Venus-Mars interaction, physical chemistry and romantic attraction directly wired.",
 "Their Moons and Suns are in aspect, giving deep emotional recognition, alongside Saturn aspects that bring seriousness and heaviness.",
 "Their composite chart paints a bigger picture: the composite Sun activates themes of power, legacy, and public identity.",
 "The composite Moon suggests an emotionally intense baseline, and composite Saturn is prominent.",
 "The synastry explains why they were drawn to each other.",
 "The composite explains what the relationship became, a power partnership with a public identity and a shared purpose that extends beyond romance.",
 "Neither chart alone tells the full story; together, they do.",
 "The Davison Chart, the Third Option",
 "The Davison Relationship Chart, named after Ronald Davison, takes a different approach from the composite.",
 "Instead of calculating mathematical midpoints, it finds the midpoint in time and space between two births, then casts a chart for that real moment and place.",
 "The result is a real astronomical chart, an actual sky that existed, rather than the abstract midpoints of a composite.",
 "Common Mistakes",
 "Treating synastry and composite as the same thing: they measure different dimensions of the relationship; reading one does not replace reading the other.",
 "Only reading the composite for new relationships: the composite describes potential that has not been activated yet; early on, synastry is usually more felt.",
 "Ignoring composite house placements: the composite Sun's house placement is arguably the single most important thing in the chart.",
 "Panicking over a bad composite chart: a composite with lots of squares and Saturn contacts does not mean a doomed relationship.",
 "It means the relationship has structure, challenges, and growth potential; many lasting marriages have difficult composite charts.",
 "Forgetting that both charts are static: neither synastry nor the composite shows how the relationship evolves over time.",
 "Frequently Asked Questions",
 "Which is more accurate, synastry or composite? Neither is; they measure different things, like a thermometer and a barometer.",
 "Can I use a composite chart for a friendship? Yes; composite charts work for any relationship that has its own identity, regardless of type.",
 "Do I need birth times for both charts? For synastry you can keep planetary aspects without exact times; for a composite, birth times are more important because the Ascendant and houses are central.",
 "What if our synastry looks great but our composite looks terrible?",
 "Strong synastry with a challenging composite often describes a couple with fantastic chemistry who struggle with the relationship as a shared project.",
 "That is information, not a death sentence.",
 "Use Both, They are Complementary",
 "Synastry and composite charts are not rivals; they are two views of the same relationship, taken from different altitudes.",
 "Synastry is street-level, the eye contact, the arguments, the chemistry.",
 "The composite is aerial, the shape of the thing, its direction, its meaning.",
 "For a full reading, you need both: start with the synastry to understand the people, then move to the composite to understand the partnership.",
]

counts = {}
counts["03"] = write_numbered("03_nuastro_composite_relationship_mirror.txt", nuastro_title, nuastro)
counts["04"] = write_numbered("04_thalira_composite_reading_guide.txt", thalira_title, thalira)
counts["05"] = write_numbered("05_synastrychart_composite_vs_synastry.txt", syn_title, syn)
print("DONE", counts)
